version: "2.1"
services:
  obsidian:
    image: obsidian:latest
    container_name: obsidian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ~/Documents/Obsidian:/config/vault
      - ./config:/config
    ports:
      - 3000:3000
    restart: unless-stopped
