name: Update Obsidian Version

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: obsidian-upstream
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: obsidianmd
          repo: obsidian-releases
          excludes: prerelease, draft

      - name: Update OBSIDIAN_VERSION in Dockerfile
        id: script
        env:
          OBSIDIAN_VERSION: ${{ steps.obsidian-upstream.outputs.release }}
        run: sed -i "s/ARG OBSIDIAN_VERSION=.*/ARG OBSIDIAN_VERSION=${OBSIDIAN_VERSION//v/}/" $GITHUB_WORKSPACE/Dockerfile

      - name: Test for changes, commit, and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_TO_COMMIT: Dockerfile
          DESTINATION_BRANCH: master
        run: |
          $GITHUB_WORKSPACE/.github/workflows/commitChange.sh
          echo "$?" >> $GITHUB_OUTPUT
  call-docker-publish:
    needs: build
    if: needs.build.outputs.output1 == 0
    uses: ./.github/workflows/docker-publish.yml
